/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Idea_Account_juctionTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Idea_Account_juctionTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Idea_Account_juction__c());
    }
}